### ISSUE TITLE
Cannot checkout or receive messages if manually checked-in by admin

### ISSUE THREAD

**Issue by paul-invary** [PeopleMakingADifference/VolunteerMgmt#61]
From Lori:

Would you happen to know IF I manually enter someone's arrival time,
does this mean that I must also manually enter his/her departure time,
i.e., s/he cannot use the app to receive broadcast messages or check out?

**Comment by pcouto64** [comment]
I don't think this is a real issue - I tried and was able to checkin if I used the admin console to set an initial checkin time.  I could not checkin or get messages if I had been checked out by the admin, but that is by design in the code.
